Fix decimals for Stata allowance (#90)
* Fix decimals for Stata allowance

* dhedge graphql is failing

* More parallelism for e2e

* Split tests in CI

* Fix approval hook

* Better validation of successful delegateCollateral command run

* yarn cache is back

* Less parallel

* Skip yarn install if possible

* cypress cache

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,21 +8,42 @@ parameters:
 commands:
   yarn-install:
     steps:
+      - run: yarn -v
+
       - run: date +"%Y-%m" > /tmp/month.txt && cat /tmp/month.txt
       - restore_cache:
           keys:
             - &yarn_cache yarn-{{ .Environment.NODE_MODULES_VERSION }}-{{ checksum "/tmp/month.txt" }}-{{ checksum "yarn.lock" }}
             - yarn-{{ .Environment.NODE_MODULES_VERSION }}-{{ checksum "/tmp/month.txt" }}-
-      - run: yarn -v
-      - run: yarn install --immutable
-      - run: sudo apt update
-      - run: sudo apt install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb lcov
+
+      # yarn's state of installation
+      - restore_cache:
+          keys:
+            - &yarn_state_cache yarn-install-state-{{ .Environment.NODE_MODULES_VERSION }}-{{ checksum "/tmp/month.txt" }}-{{ checksum "yarn.lock" }}
+            - yarn-install-state-{{ .Environment.NODE_MODULES_VERSION }}-{{ checksum "/tmp/month.txt" }}-
+
+      - run:
+          name: Fallback to installing node modules in case of cache corruption
+          command: |-
+            # Check if we restored cache and have node_modules already
+            if [ -f "node_modules/.yarn-state.yml" ] && [ -f ".yarn/install-state.gz" ]; then
+              echo "node_modules restored from cache"
+              exit 0
+            else
+              echo "node_modules could not be restored from cache, activating fallback installation"
+              yarn install --immutable
+            fi
+
       - save_cache:
           key: *yarn_cache
           paths:
-            - '~/.cache'
-            - '~/.yarn/berry'
             - 'node_modules'
+            - '~/.cache/Cypress'
+
+      - save_cache:
+          key: *yarn_state_cache
+          paths:
+            - '.yarn/install-state.gz'
 
   install-foundry:
     steps:
@@ -139,14 +160,21 @@ jobs:
           path: 'coverage'
 
   e2e:
+    parameters:
+      dir:
+        type: string
+      parallelism:
+        type: integer
     docker:
       - image: cimg/node:<< pipeline.parameters.node-version >>
     resource_class: large
-    parallelism: 3
+    parallelism: << parameters.parallelism >>
     steps:
       - checkout
       - install-foundry
       - yarn-install
+      - run: sudo apt update
+      - run: sudo apt install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb lcov
 
       - run: date +"%Y-%W" > /tmp/week.txt && cat /tmp/week.txt
       - restore_cache:
@@ -172,7 +200,7 @@ jobs:
             echo "0" > /tmp/cypress_exit_code
             export NODE_ENV=test
             export CYPRESS_INFURA_KEY=$INFURA_KEY
-            circleci tests glob 'cypress/e2e/**/*.e2e.js' | circleci tests run --verbose --split-by=timings --command="xargs yarn cypress run --e2e --spec" || echo $? > /tmp/cypress_exit_code
+            circleci tests glob 'cypress/e2e/<< parameters.dir >>/*.e2e.js' | circleci tests run --verbose --split-by=timings --command="xargs yarn cypress run --e2e --spec" || echo $? > /tmp/cypress_exit_code
 
       - save_cache:
           key: *anvil-fork-cache
@@ -351,14 +379,27 @@ workflows:
       #    working_directory: 'contracts/debt-repayer-base-andromeda'
 
       #- cy
-      - e2e
+      - e2e:
+          name: e2e-base
+          dir: '8453-andromeda'
+          parallelism: 2
+      - e2e:
+          name: e2e-arbitrum
+          dir: '42161-main'
+          parallelism: 2
+      - e2e:
+          name: e2e-mainnet
+          dir: '1-main'
+          parallelism: 1
 
       - ipfs:
           requires:
             - checks
             - tests
             #- cy
-            - e2e
+            - e2e-base
+            - e2e-arbitrum
+            - e2e-mainnet
           filters:
             branches:
               only:
